name=digitalWriteFast_zephyr
version=0.0.42
author=kurte
maintainer=kurte
sentence=A library to extend digital pins on STM32 zephyr boards
paragraph=This library adds things like digitalWriteFast and pin names support.
category=Communication
url=https://www.arduino.cc/
architectures=architectures=zephyr,zephyr_main,zephyr_contrib
includes=digitalWriteFast_zephyr.h